import { ParameterType } from 'typedoc';
import { DEFAULT_SIDEBAR_OPTIONS } from '../options.js';

/**
 * **autoConfiguration**
 *
 * Set to `false` to disable sidebar generation. Defaults to `true`.
 *
 * **typescript**
 *
 * Set to `true` to generate a TypeScript file. Defaults to `false` (CommonJs).
 *
 * **pretty**
 *
 * Pretty format the sidebar JSON. Defaults to `false`.
 *
 * **deprecatedItemClassName**
 *
 * The class name to apply to deprecated items in the sidebar. Defaults to `"typedoc-sidebar-item-deprecated"`.
 *
 * Please see the [sidebar guide](/plugins/docusaurus/guides/sidebar) for additional information on sidebar setup.
 *
 * ```js  filename="docusaurus.config.js"
 * {
 *   plugins: [
 *     [
 *       'docusaurus-plugin-typedoc',
 *       {
 *         "sidebar": {
 *           "autoConfiguration": true,
 *           "pretty": false,
 *           "typescript": false,
 *           "deprecatedItemClassName": "typedoc-sidebar-item-deprecated"
 *         }
 *       }
 *     ]
 *   ]
 * }
 * ```
 *
 * @omitExample
 *
 */
export const sidebar = {
  help: 'Configures the autogenerated sidebar.',
  type: ParameterType.Mixed,
  defaultValue: DEFAULT_SIDEBAR_OPTIONS,
  validate(value) {
    const validKeys = Object.keys(DEFAULT_SIDEBAR_OPTIONS);
    for (const key of Object.keys(value)) {
      if (!validKeys.includes(key)) {
        throw new Error(
          `[typedoc-docusaurus-theme] '${key}' is not a valid sidebar option. Allowed keys are: ${validKeys.join(
            ', ',
          )}`,
        );
      }
    }
  },
};

/**
 * Path to the docs content directory on the file system, relative to the Docusaurus site directory.
 *
 * This should match the `docs.path` value configured in the `docusaurus.config.js` docs preset.
 *
 * *Note: `docusaurus-plugin-typedoc` will automatically attempt to set this option based on your Docusaurus configuration.*
 */
export const docsPath = {
  help: 'The value of the Docusaurus `docs.path` config option.',
  type: ParameterType.Path,
  defaultValue: './docs',
};

/**
 * By default, Docusaurus applies custom parsing logic to extract number prefixes from file names.
 *
 * You can disable this behavior by setting `numberPrefixParser: false` in the `docs` preset of your `docusaurus.config.js` file.
 * This option should match the value configured there.
 *
 * *Note: `docusaurus-plugin-typedoc` will automatically attempt to set this option based on your Docusaurus configuration.*
 *
 * @example false
 */
export const numberPrefixParser = {
  help: 'The value of the Docusaurus `numberPrefixParser` option.',
  type: ParameterType.Boolean,
  defaultValue: true,
};
