/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  mySidebar: [{ type: 'autogenerated', dirName: '.' }],

  /*mySidebar: [
    {
      type: 'category',
      label: 'My API',
      link: { type: 'doc', id: 'api-1/index' },
      items: [{ type: 'autogenerated', dirName: 'api-1' }],
    },
    {
      type: 'category',
      label: 'My API 2',
      //link: { type: 'doc', id: 'api-1/index' },
      items: [{ type: 'autogenerated', dirName: 'api-2' }],
    },
    {
      type: 'category',
      label: 'My API 3',
      //link: { type: 'doc', id: 'api-1/index' },
      items: [{ type: 'autogenerated', dirName: 'api-3' }],
    },
  ],*/

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
