export const KIND_DEFAULTS: Record<string, string> = {
  'kind.class.singular': 'Class',
  'kind.class.plural': 'Classes',
  'kind.constructor.singular': 'Constructor',
  'kind.constructor.plural': 'Constructors',
  'kind.enum.singular': 'Enumeration',
  'kind.enum.plural': 'Enumerations',
  'kind.enum-member.singular': 'Enumeration Member',
  'kind.enum-member.plural': 'Enumeration Members',
  'kind.event.singular': 'Event',
  'kind.event.plural': 'Events',
  'kind.function.singular': 'Function',
  'kind.function.plural': 'Functions',
  'kind.interface.singular': 'Interface',
  'kind.interface.plural': 'Interfaces',
  'kind.method.singular': 'Method',
  'kind.method.plural': 'Methods',
  'kind.module.singular': 'Module',
  'kind.module.plural': 'Modules',
  'kind.namespace.singular': 'Namespace',
  'kind.namespace.plural': 'Namespaces',
  'kind.variable.singular': 'Variable',
  'kind.variable.plural': 'Variables',
  'kind.parameter.singular': 'Parameter',
  'kind.parameter.plural': 'Parameters',
  'kind.property.singular': 'Property',
  'kind.property.plural': 'Properties',
  'kind.reference.singular': 'Reference',
  'kind.reference.plural': 'References',
  'kind.type-alias.singular': 'Type alias',
  'kind.type-alias.plural': 'Type Aliases',
  'kind.type-parameter.singular': 'Type parameter',
  'kind.type-parameter.plural': 'Type parameters',
};

export const SINGULAR_KIND_KEY_MAP: Record<string, string> = {
  ['Class']: 'kind.class.singular',
  ['Constructor']: 'kind.constructor.singular',
  ['Enumeration']: 'kind.enum.singular',
  ['Enumeration Member']: 'kind.enum-member.singular',
  ['Event']: 'kind.event.singular',
  ['Function']: 'kind.function.singular',
  ['Interface']: 'kind.interface.singular',
  ['Method']: 'kind.method.singular',
  ['Module']: 'kind.module.singular',
  ['Namespace']: 'kind.namespace.singular',
  ['Variable']: 'kind.variable.singular',
  ['Parameter']: 'kind.parameter.singular',
  ['Property']: 'kind.property.singular',
  ['Reference']: 'kind.reference.singular',
  ['Type alias']: 'kind.type-alias.singular',
  ['Type parameter']: 'kind.type-parameter.singular',
};

export const PLURAL_KIND_KEY_MAP: Record<string, string> = {
  ['Classes']: 'kind.class.plural',
  ['Constructors']: 'kind.constructor.plural',
  ['Enumerations']: 'kind.enum.plural',
  ['Enumeration Members']: 'kind.enum-member.plural',
  ['Events']: 'kind.event.plural',
  ['Functions']: 'kind.function.plural',
  ['Interfaces']: 'kind.interface.plural',
  ['Methods']: 'kind.method.plural',
  ['Modules']: 'kind.module.plural',
  ['Namespaces']: 'kind.namespace.plural',
  ['Variables']: 'kind.variable.plural',
  ['Parameters']: 'kind.parameter.plural',
  ['Properties']: 'kind.property.plural',
  ['References']: 'kind.reference.plural',
  ['Type Aliases']: 'kind.type-alias.plural',
  ['Type parameters']: 'kind.type-parameter.plural',
};
