/**
 * Describes the options declared by the plugin.
 *
 * @privateRemarks
 *
 * THIS FILE IS AUTO GENERATED FROM THE OPTIONS CONFIG. DO NOT EDIT DIRECTLY
 *
 * @module
 */
export interface PluginOptions {
  /**
   * Configures the autogenerated `_sidebar.md file`.
   */
  sidebar: Sidebar;
}

/**
 *
 *
 * @category Options
 */
export interface Sidebar {
  autoConfiguration: boolean;
  heading: string;
}
