import { ParameterType } from 'typedoc';
import { DEFAULT_SIDEBAR_OPTIONS } from '../options';

/**
 * **sidebar.autoConfiguration**
 *
 * Set to `false` to disable sidebar generation. Defaults to true.
 *
 * **sidebar.format**
 *
 * Eenables backward compatibility with VuePress. Available options [`"vitepress"`, `"vuepress1"`, `"vuepress2"`]. Defaults to `"vitepress"`.
 *
 * **sidebar.collapsed**
 *
 * Determines if sidebar items with children are open or closed. Set `collapsed` to `false` to set sidebar items as open by default.
 *
 * https://vitepress.dev/reference/default-theme-sidebar#collapsible-sidebar-groups
 *
 * **sidebar.pretty**
 *
 * Pretty format the sidebar JSON.
 *
 */
export const sidebar = {
  help: 'Configures the autogenerated VitePress sidebar.',
  type: ParameterType.Mixed,
  defaultValue: DEFAULT_SIDEBAR_OPTIONS,
};
