import * as fs from 'fs';
import * as path from 'path';

import { PluginOptions } from './types';

export const writeSidebar = (siteDir: string, options: PluginOptions) => {
  const sidebarPath = path.resolve(siteDir, options.sidebar.sidebarFile);
  if (!fs.existsSync(path.dirname(sidebarPath))) {
    fs.mkdirSync(path.dirname(sidebarPath));
  }
  fs.writeFileSync(
    sidebarPath,
    `module.exports=[{type:'autogenerated',dirName:'${options.out}'}];`,
  );
};
