import * as fs from 'fs';
import * as path from 'path';

import { PluginOptions } from './types';

export const shouldWriteSidebar = (siteDir: string, options: PluginOptions) => {
  const sidebarPath = path.resolve(siteDir, options.sidebar.sidebarFile);
  return fs.existsSync(sidebarPath);
};

export const writeSidebar = (siteDir: string, options: PluginOptions) => {
  const sidebarPath = path.resolve(siteDir, options.sidebar.sidebarFile);
  fs.writeFileSync(
    sidebarPath,
    `module.exports=[{type:'autogenerated',dirName:'${options.out}'}]`,
  );
};
