/*
 * THIS FILE IS AUTO GENERATED FROM THE OPTIONS CONFIG. DO NOT EDIT DIRECTLY
 */
/**
 * Describes the options declared by the plugin.
 */
export interface PluginOptions {
  /**
   * Configures the autogenerated `_Sidebar.md file`.
   */
  sidebar: Sidebar;
}

export interface Sidebar {
  autoConfiguration: boolean;
  heading: string;
}
