name: CI [typedoc-docusaurus-theme]
on:
  push:
    paths:
      - 'packages/typedoc-docusaurus-theme/**'
      - '!packages/typedoc-docusaurus-theme/README.md'
      - '!packages/typedoc-docusaurus-theme/CHANGELOG.md'
      - '!packages/typedoc-docusaurus-theme/package.json'
    branches:
      - main
      - release
      - beta
  pull_request:
    paths:
      - 'packages/typedoc-docusaurus-theme/**'
      - '!packages/typedoc-docusaurus-theme/README.md'
      - '!packages/typedoc-docusaurus-theme/CHANGELOG.md'
      - '!packages/typedoc-docusaurus-theme/package.json'
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: HUSKY=0 pnpm install

      - name: Lint
        run: pnpm --filter typedoc-docusaurus-theme run lint

      - name: Build
        run: pnpm --filter typedoc-docusaurus-theme run build

      - name: Test
        run: pnpm --filter typedoc-docusaurus-theme run test
