name: CI [typedoc-docusaurus-theme]
on:
  push:
    paths:
      - 'packages/typedoc-docusaurus-theme/**'
      - '!packages/typedoc-docusaurus-theme/README.md'
      - '!packages/typedoc-docusaurus-theme/CHANGELOG.md'
      - '!packages/typedoc-docusaurus-theme/package.json'
    branches:
      - main
      - release
      - beta
  pull_request:
    paths:
      - 'packages/typedoc-docusaurus-theme/**'
      - '!packages/typedoc-docusaurus-theme/README.md'
      - '!packages/typedoc-docusaurus-theme/CHANGELOG.md'
      - '!packages/typedoc-docusaurus-theme/package.json'
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18', '20.19.0']
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install
        run: HUSKY=0 npm ci
      - name: Lint
        if: matrix.node == '20.19.0'
        run: npm run lint --workspace typedoc-docusaurus-theme
      - name: Build
        if: matrix.node == '18'
        run: npm run build --workspace typedoc-plugin-markdown --workspace typedoc-docusaurus-theme
      - name: Test
        if: matrix.node == '18'
        run: npm run test --workspace typedoc-docusaurus-theme
