name: CI
on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'packages/typedoc-plugin-markdown/**'
      - '!packages/typedoc-plugin-markdown/README.md'
      - '!packages/typedoc-plugin-markdown/CHANGELOG.md'
      - '!packages/typedoc-plugin-markdown/package.json'
    branches:
      - main
      - release
      - beta
      - remove-jest
  pull_request:
    paths:
      - 'packages/typedoc-plugin-markdown/**'
      - '!packages/typedoc-plugin-markdown/README.md'
      - '!packages/typedoc-plugin-markdown/CHANGELOG.md'
      - '!packages/typedoc-plugin-markdown/package.json'
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node: ['18']
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install
        run: HUSKY=0 npm ci
      - name: Lint
        run: npm run lint --workspace typedoc-plugin-markdown
      - name: Build
        run: npm run build-all
      - name: Test
        run: npm run test-all
