name: CI
on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'packages/typedoc-plugin-markdown/**'
      - '!packages/typedoc-plugin-markdown/README.md'
      - '!packages/typedoc-plugin-markdown/CHANGELOG.md'
      - '!packages/typedoc-plugin-markdown/package.json'
    branches:
      - main
      - release
      - beta
  pull_request:
    paths:
      - 'packages/typedoc-plugin-markdown/**'
      - '!packages/typedoc-plugin-markdown/README.md'
      - '!packages/typedoc-plugin-markdown/CHANGELOG.md'
      - '!packages/typedoc-plugin-markdown/package.json'
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node: ['18']
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: HUSKY=0 pnpm install

      - name: Lint
        run: pnpm --filter typedoc-plugin-markdown run lint

      - name: Build
        run: pnpm build-all

      - name: Test
        run: pnpm test-all
